const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT = 409;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;

module.exports = { NOT_FOUND, BAD_REQUEST, INTERNAL_SERVER_ERROR, CONFLICT, UNAUTHORIZED, FORBIDDEN };
